apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-lab-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-lab-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: vault-lab Root CA
  secretName: vault-lab-root-ca
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: vault-lab-selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-lab-ca-issuer
spec:
  ca:
    secretName: vault-lab-root-ca
