apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-test-secret
  namespace: external-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-a-jwt-store
    kind: SecretStore
  target:
    name: eso-test-secret
    creationPolicy: Owner
  data:
    - secretKey: value
      remoteRef:
        key: secret/data/eso-test
        property: value
